# Generated by Django 3.1.6 on 2021-02-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Am',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('temp', models.IntegerField(null=True)),
                ('prec', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Eve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('temp', models.IntegerField(null=True)),
                ('prec', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('temp', models.IntegerField(null=True)),
                ('prec', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, null=True)),
                ('outlook', models.CharField(max_length=300, null=True)),
                ('eve_temp', models.IntegerField(null=True)),
                ('am', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.am')),
                ('eve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.eve')),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pm')),
            ],
        ),
    ]
