# Generated by Django 3.1.6 on 2021-03-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_report_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='York, GB', max_length=25),
        ),
        migrations.AlterField(
            model_name='report',
            name='am',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.am'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pm'),
        ),
    ]
